apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      name: spring-pod
      labels:
        app: spring
    spec:
      containers:
        - name: webserver1
          image: 'harishdurai/applicationtier:latest'
          ports:
            - containerPort: 8080

       